# Generated by Django 4.1 on 2022-10-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='Paper_title',
            field=models.CharField(help_text='Title of the published manuscript/report.', max_length=200, verbose_name='Paper Title'),
        ),
    ]
