# Generated by Django 4.1 on 2022-09-08 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_users_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unique_identifier', models.CharField(max_length=20)),
                ('Study_group', models.CharField(choices=[('SST', 'Superficial skin and throat'), ('IG', 'Invasive GAS'), ('ARF', 'ARF'), ('ASPGN', 'APSGN')], max_length=5)),
                ('Paper_title', models.CharField(max_length=200)),
                ('Paper_link', models.CharField(max_length=200)),
                ('Year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('Disease', models.CharField(max_length=200)),
                ('Study_design', models.CharField(max_length=200)),
                ('Study_design_other', models.CharField(max_length=200)),
                ('Study_description', models.CharField(max_length=200)),
                ('Case_definition', models.CharField(max_length=200)),
                ('Case_findings', models.CharField(max_length=200)),
                ('Case_findings_other', models.CharField(max_length=200)),
                ('Data_source', models.CharField(max_length=200)),
                ('Case_cap_meth', models.CharField(max_length=200)),
                ('Case_cap_meth_other', models.CharField(max_length=200)),
                ('Coverage', models.CharField(max_length=200)),
                ('Jurisdiction', models.CharField(max_length=200)),
                ('Specific_region', models.CharField(max_length=200)),
                ('Climate', models.CharField(max_length=200)),
                ('Aria_remote', models.CharField(max_length=200)),
                ('Population_group_strata', models.CharField(max_length=200)),
                ('Population_denom', models.CharField(max_length=200)),
                ('Age_original', models.CharField(max_length=200)),
                ('Age_general', models.CharField(max_length=200)),
                ('Age_min', models.IntegerField()),
                ('Age_max', models.IntegerField()),
                ('Burden_measure', models.CharField(max_length=200)),
                ('Ses_reported', models.BooleanField()),
                ('Mortality_data', models.BooleanField()),
                ('Method_limitations', models.BooleanField()),
                ('Limitations_identified', models.BooleanField()),
                ('Other_points', models.CharField(max_length=200)),
            ],
        ),
    ]
