# Generated by Django 4.1 on 2022-10-07 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_studies_paper_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='Paper_link',
            field=models.CharField(blank=True, help_text='URL or doi to facilitate access to the source manuscript/report, full access will depend on open/institutional access permissions set by each journal.', max_length=200, verbose_name='Link to Paper Download'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year of publication of manuscript/report.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Publication Year'),
        ),
    ]
