# Generated by Django 4.1 on 2022-09-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_database_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='about',
        ),
        migrations.AddField(
            model_name='users',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='institution',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='profession',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
