# Generated by Django 4.1 on 2022-09-09 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_studies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='Age_general',
            field=models.CharField(choices=[('ALL', 'All'), ('AD', 'Adults'), ('C', 'Children'), ('AL', 'Adolescents'), ('EA', 'Elderly Adults')], max_length=5),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Age_max',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(150.0)]),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Age_min',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(150.0)]),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Disease',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Limitations_identified',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Study_design',
            field=models.CharField(choices=[('CST', 'Cross-sectional'), ('P', 'Prospective'), ('RP', 'Retrospective'), ('PRP', 'Prospective and Retrospective'), ('CS', 'Case series'), ('R', 'Report'), ('PC', 'Prospective cohort'), ('RPR', 'Retrospective review'), ('RA', 'Review article'), ('RPC', 'Retrospective cohort'), ('O', 'Other')], max_length=3),
        ),
    ]
