# Generated by Django 4.1 on 2022-09-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "database",
            "0004_remove_users_about_users_country_users_institution_and_more",
        ),
        ("database", "0008_delete_customer"),
    ]

    operations = []
