# Generated by Django 4.1 on 2022-09-15 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0014_alter_results_age_general"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_staff",
        ),
        migrations.AddField(
            model_name="users",
            name="can_view_data",
            field=models.BooleanField(
                default=True, verbose_name="Allow View Access to Database"
            ),
        ),
        migrations.AlterField(
            model_name="results",
            name="Age_general",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ALL", "All ages"),
                    ("AD", "Adult"),
                    ("C", "Children"),
                    ("AL", "Adolescents"),
                    ("I", "Infant"),
                    ("M", "Mix"),
                ],
                max_length=5,
                verbose_name="Age Category",
            ),
        ),
        migrations.AlterField(
            model_name="results",
            name="Age_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MaxValueValidator(150.0)],
                verbose_name="Maximum Age (years)",
            ),
        ),
        migrations.AlterField(
            model_name="results",
            name="Age_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MaxValueValidator(150.0)],
                verbose_name="Minimum Age (years)",
            ),
        ),
        migrations.AlterField(
            model_name="results",
            name="Age_original",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Age Category (Original)"
            ),
        ),
        migrations.AlterField(
            model_name="results",
            name="Age_standardisation",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("?", "N/A")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="results",
            name="Country",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="results",
            name="Dataset_name",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("?", "N/A")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="results",
            name="Defined_ARF",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("?", "N/A")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="results",
            name="Focus_of_study",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="results",
            name="GAS_attributable_fraction",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("?", "N/A")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="results",
            name="Indigenous_population",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="results",
            name="Indigenous_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="results",
            name="Interpolated_from_graph",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("?", "N/A")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="results",
            name="Jurisdiction",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="results",
            name="Measure",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="results",
            name="Mortality_flag",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("?", "N/A")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="results",
            name="Notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="results",
            name="Proportion",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("?", "N/A")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="results",
            name="Recurrent_ARF_flag",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("?", "N/A")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="results",
            name="Specific_location",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Age_general",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ALL", "All"),
                    ("AD", "Adults"),
                    ("C", "Children"),
                    ("AL", "Adolescents"),
                    ("EA", "Elderly Adults"),
                ],
                max_length=5,
                verbose_name="Age Category",
            ),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Age_original",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Age Category (Original)"
            ),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Aria_remote",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Case_cap_meth",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Case_cap_meth_other",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Case_definition",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Case_findings",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Case_findings_other",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Climate",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Coverage",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Data_source",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Jurisdiction",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Method_limitations",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Mortality_data",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Paper_link",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Link to Paper Download"
            ),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Paper_title",
            field=models.CharField(max_length=200, verbose_name="Paper Title"),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Population_denom",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Population_group_strata",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Ses_reported",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Specific_region",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Study_description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Study_design",
            field=models.CharField(
                choices=[
                    ("CS", "Case series"),
                    ("CST", "Cross-sectional"),
                    ("P", "Prospective"),
                    ("PRP", "Prospective and Retrospective"),
                    ("PC", "Prospective cohort"),
                    ("R", "Report"),
                    ("RP", "Retrospective"),
                    ("RPR", "Retrospective review"),
                    ("RPC", "Retrospective cohort"),
                    ("RA", "Review article"),
                    ("O", "Other"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Study_design_other",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Study_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SST", "Superficial skin and throat"),
                    ("IG", "Invasive GAS"),
                    ("ARF", "ARF"),
                    ("ASPGN", "APSGN"),
                ],
                max_length=5,
                verbose_name="Study Group",
            ),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Unique_identifier",
            field=models.CharField(max_length=20, verbose_name="Unique Identifier"),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2100),
                ],
                verbose_name="Publication Year",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Account Enabled"),
        ),
        migrations.AlterField(
            model_name="users",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="Is Administrator"),
        ),
    ]
