# Generated by Django 4.1 on 2022-09-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_studies_age_general_alter_studies_age_max_and_more'),
        ('database', '0015_remove_users_is_admin_remove_users_is_staff_and_more'),
    ]

    operations = [
    ]
