# Generated by Django 4.1 on 2022-09-15 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_merge_20220916_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='Age_general',
            field=models.CharField(blank=True, choices=[('ALL', 'All'), ('AD', 'Adults'), ('C', 'Children'), ('AL', 'Adolescents'), ('EA', 'Elderly Adults')], max_length=5, verbose_name='Age Category'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Age_original',
            field=models.CharField(blank=True, max_length=200, verbose_name='Age Category (Original)'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Aria_remote',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Case_cap_meth',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Case_cap_meth_other',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Case_definition',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Case_findings',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Case_findings_other',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Climate',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Coverage',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Data_source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Jurisdiction',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Method_limitations',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('?', 'N/A')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Mortality_data',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('?', 'N/A')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Paper_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Link to Paper Download'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Population_denom',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Population_group_strata',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Ses_reported',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('?', 'N/A')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Specific_region',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Study_description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Study_design_other',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studies',
            name='Year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Publication Year'),
        ),
    ]
