# Generated by Django 4.1 on 2022-09-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_studies_age_general_alter_studies_age_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='Study_group',
            field=models.CharField(blank=True, choices=[('SST', 'Superficial skin and throat'), ('IG', 'Invasive GAS'), ('ARF', 'ARF'), ('ASPGN', 'APSGN')], max_length=30, verbose_name='Study Group'),
        ),
    ]
