# Generated by Django 4.1 on 2022-09-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_results_point_estimate_original_alter_results_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studies',
            name='Notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
