# Generated by Django 4.1 on 2022-10-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0018_studies_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="is_admin",
        ),
        migrations.AlterField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="Staff status",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="Superuser status",
            ),
        ),
    ]
