# Generated by Django 4.1 on 2022-10-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_remove_users_is_admin_alter_users_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studygroup.ARF_studies',
            fields=[
            ],
            options={
                'verbose_name': 'ARF Studies',
                'verbose_name_plural': 'ARF Studies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('database.studies',),
        ),
        migrations.CreateModel(
            name='Studygroup.ASPGN_studies',
            fields=[
            ],
            options={
                'verbose_name': 'ASPGN Studies',
                'verbose_name_plural': 'ASPGN Studies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('database.studies',),
        ),
        migrations.CreateModel(
            name='Studygroup.IG_studies',
            fields=[
            ],
            options={
                'verbose_name': 'Invasive GAS Studies',
                'verbose_name_plural': 'Invasive GAS Studies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('database.studies',),
        ),
        migrations.CreateModel(
            name='Studygroup.SST_studies',
            fields=[
            ],
            options={
                'verbose_name': 'Superficial Skin & Throat Studies',
                'verbose_name_plural': 'Superficial Skin & Throat Studies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('database.studies',),
        ),
        migrations.CreateModel(
            name='StudyStudygroup.ARF_results',
            fields=[
            ],
            options={
                'verbose_name': 'ARF Results',
                'verbose_name_plural': 'ARF Results',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('database.results',),
        ),
        migrations.CreateModel(
            name='StudyStudygroup.ASPGN_results',
            fields=[
            ],
            options={
                'verbose_name': 'ASPGN Results',
                'verbose_name_plural': 'ASPGN Results',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('database.results',),
        ),
        migrations.CreateModel(
            name='StudyStudygroup.IG_results',
            fields=[
            ],
            options={
                'verbose_name': 'Invasive GAS Results',
                'verbose_name_plural': 'Invasive GAS Results',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('database.results',),
        ),
        migrations.CreateModel(
            name='StudyStudygroup.SST_results',
            fields=[
            ],
            options={
                'verbose_name': 'Superficial Skin & Throat Results',
                'verbose_name_plural': 'Superficial Skin & Throat Results',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('database.results',),
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name': 'Result (Any Group)', 'verbose_name_plural': 'Results (Any Group)'},
        ),
        migrations.AlterModelOptions(
            name='studies',
            options={'verbose_name': 'Study (Any Group)', 'verbose_name_plural': 'Studies (Any Group)'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='studies',
            name='Unique_identifier',
            field=models.CharField(blank=True, help_text='Internal use only', max_length=20, null=True, verbose_name='Unique Identifier'),
        ),
    ]
