# Generated by Django 4.1 on 2022-10-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0021_alter_results_age_general"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studies",
            name="Paper_link",
            field=models.CharField(
                blank=True,
                help_text="URL or doi to facilitate access to the source manuscript/report, full access will depend on open/institutional access permissions set by each journal.",
                max_length=1000,
                verbose_name="Link to Paper Download",
            ),
        ),
        migrations.AlterField(
            model_name="studies",
            name="Paper_title",
            field=models.CharField(
                help_text="Title of the published manuscript/report.",
                max_length=500,
                verbose_name="Paper Title",
            ),
        ),
    ]
