# Generated by Django 4.1 on 2022-10-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0024_alter_results_focus_of_study_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="is_staff",
        ),
    ]
